[build]
    command = "make build"

[build.environment]
    # Change this path with the path to your repository
    GO_IMPORT_PATH = "github.com/cbosss/functions-playground"

[[redirects]]
    from = "/"
    to = "/.netlify/functions/dump"
    status = 200

[[redirects]]
    from = "/*"
    to = "/.netlify/functions/dump"
    status = 200