[[redirects]]
    from = "/broken/*"
    to = "https://cbosss-site-b.netlify.app"
    status = 200

[[redirects]]
    from = "/fixed/*"
    to = "https://cbosss-site-b.netlify.app/"
    status = 200

[[redirects]]
    from = "/splat/*"
    to = "https://cbosss-site-b.netlify.app/:splat"
    status = 200